# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno build plug and push

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.1

      - name: Verify formatting
        run: deno fmt --check
        
      - name: Setup silverbullet
        run: deno install -f --name silverbullet  --unstable-kv --unstable-worker-options -A https://get.silverbullet.md

      - name: Add Deno bin to PATH
        run: echo "$HOME/.deno/bin" >> $GITHUB_PATH

      - name: Verify PATH
        run: echo $PATH

      - name: Silverbullet version
        run: silverbullet --version

      - name: Run Deno build task
        run: deno task build

      - name: Commit and push if on main
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add graphview.plug.js || true
          git commit -m "Auto update graphview.plug.js [skip ci]" || true
          git push
